<?php $campaigns = (array)($data['data'] ?? []); $meta = (array)($data['meta'] ?? []); ?>
<div class="container py-4 py-lg-5" data-campaigns-root>
    <div class="d-flex flex-wrap align-items-start justify-content-between gap-3 mb-4"><div><h1 class="h2 mb-1">Campañas de notificaciones</h1><p class="text-body-secondary mb-0">Envía ahora o programa notificaciones mediante los transportes instalados.</p></div><button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#campaign-form">Nueva campaña</button></div>
    <div class="collapse mb-4" id="campaign-form"><div class="card"><div class="card-body"><form class="needs-validation" data-campaign-form novalidate>
        <div class="row g-3"><div class="col-12 col-lg-6"><label class="form-label" for="campaign-name">Nombre interno</label><input class="form-control" id="campaign-name" name="name" maxlength="160" required></div><div class="col-12 col-lg-6"><label class="form-label" for="campaign-title">Título</label><input class="form-control" id="campaign-title" name="title" maxlength="190" required></div>
        <div class="col-12"><label class="form-label" for="campaign-message">Mensaje</label><textarea class="form-control" id="campaign-message" name="message" rows="4" required></textarea></div>
        <div class="col-12 col-lg-6"><span class="form-label d-block">Canales</span><div class="d-flex gap-4"><div class="form-check"><input class="form-check-input" id="campaign-inbox" name="channels[]" value="inbox" type="checkbox"><label class="form-check-label" for="campaign-inbox">Inbox</label></div><div class="form-check"><input class="form-check-input" id="campaign-email" name="channels[]" value="email" type="checkbox"><label class="form-check-label" for="campaign-email">Correo</label></div></div></div>
        <div class="col-12 col-lg-6"><label class="form-label" for="campaign-scheduled">Fecha programada <span class="text-body-secondary">(opcional)</span></label><input class="form-control" id="campaign-scheduled" name="scheduled_at" type="datetime-local"></div>
        <div class="col-12"><label class="form-label" for="campaign-recipients">Destinatarios</label><textarea class="form-control font-monospace" id="campaign-recipients" name="recipients" rows="5" required placeholder="email:usuario@example.com&#10;inbox:42"></textarea><div class="form-text">Uno por línea. Si eliges varios canales, indica el prefijo <code>email:</code> o <code>inbox:</code>.</div></div>
        <input type="hidden" name="template_id" value="notification"><div class="col-12"><button class="btn btn-primary" type="submit">Crear campaña</button></div></div>
    </form></div></div></div>
    <form class="row g-2 mb-3" data-campaign-filters><div class="col-12 col-md-4"><label class="visually-hidden" for="campaign-status">Estado</label><select class="form-select" id="campaign-status" name="status"><option value="all">Todos los estados</option><?php foreach (['scheduled' => 'Programadas', 'running' => 'En proceso', 'paused' => 'Pausadas', 'completed' => 'Completadas', 'failed' => 'Con errores', 'cancelled' => 'Canceladas'] as $value => $label): ?><option value="<?= $value ?>" <?= ($meta['status'] ?? '') === $value ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></div><div class="col-12 col-md-auto"><button class="btn btn-outline-secondary" type="submit">Filtrar</button></div></form>
    <div data-campaign-list><?php include __DIR__ . '/_list.php'; ?></div>
</div>
