ALTER TABLE media ADD COLUMN alt_text TEXT NOT NULL DEFAULT '';
ALTER TABLE media ADD COLUMN metadata_json TEXT NULL;
ALTER TABLE media ADD COLUMN variants_json TEXT NULL;
ALTER TABLE media ADD COLUMN status TEXT NOT NULL DEFAULT 'ready';
