<?php

class Robots
{
    public function index($routeParams = []): void
    {
        header('Content-Type: text/plain; charset=UTF-8');
        echo $this->render();
        exit;
    }

    private function render(): string
    {
        $disallowPaths = [
            '/admin/',
            '/ajax/',
            '/api/',
            '/auth/',
            '/core/',
            '/app/',
            '/storage/',
            '/packages/',
            '/vendor/',
        ];

        $agents = [
            '*',
            'GPTBot',
            'ChatGPT-User',
            'Google-Extended',
            'ClaudeBot',
            'CCBot',
            'PerplexityBot',
            'Applebot-Extended',
            'Bytespider',
        ];

        $lines = [
            '# Dynamic robots.txt generated by the application.',
            '# Public content is crawlable; private and system areas stay blocked.',
            '',
        ];

        foreach ($agents as $agent) {
            $lines[] = 'User-agent: ' . $agent;
            $lines[] = 'Allow: /';

            foreach ($disallowPaths as $path) {
                $lines[] = 'Disallow: ' . $path;
            }

            $lines[] = '';
        }

        $lines[] = 'Sitemap: ' . rtrim(site_url, '/') . '/sitemap.xml';

        return implode("\n", $lines) . "\n";
    }
}
